name: Deploy to Linode Compute Instance

on:
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: dotnet build
      #- name: Run Tests
      #  run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      #- name: Code Coverage Summary Report
      #  uses: irongut/CodeCoverageSummary@v1.3.0
      #  with:
      #    filename: ./coverage/**/coverage.cobertura.xml
      #    badge: true
      #    fail_below_min: true
      #    format: markdown
      #    hide_branch_rate: false
      #    hide_complexity: true
      #    indicators: true
      #    output: both
      #    thresholds: '1 50'
          
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio_v3:latest
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull and Run Docker Image on Linode Remote Server
        uses: appleboy/ssh-action@master
        env:
          HOST_PORT: ${{ secrets.HOST_PORT }}
          DOCKER_NETWORK: ${{ secrets.DOCKER_NETWORK }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }} 
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: HOST_PORT,DOCKER_NETWORK
          script: |
            export envArray=( $HOST_PORT $DOCKER_NETWORK ) \
            && docker pull thoughtspring/portfolio_v3 \
            && if [[ -z $(docker container ls -a | grep "portfolio_v3") ]]; \
            then echo "No container found. Starting portfolio_v3 container..."; \
            else docker stop portfolio_v3 && docker rm portfolio_v3; \
            fi \
            && docker run -d -p "${envArray[0]}":80 --network "${envArray[1]}" --name portfolio_v3 --restart always \
            thoughtspring/portfolio_v3 \
            && exit \
            && exit 0;